services:

  spark:
    image: apache/spark:3.5.0
    container_name: spark
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./spark_jobs:/spark_jobs

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      - spark
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/data
    ports:
      - "8081:8080"
